plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
webrick:
  headers:
    Access-Control-Allow-Origin: "https://not.ninja"
    Content-Security-Policy: "default-src 'self'; script-src 'self' *.cloudfront.net cdnjs.cloudflare.com *.google-analytics.com; style-src 'self' *.cloudfront.net cdnjs.cloudflare.com; font-src 'self' *.cloudfront.net cdnjs.cloudflare.com; img-src 'self' *.cloudfront.net *.google-analytics.com; connect-src 'self' *.google-analytics.com"
    Referrer-Policy: "no-referrer"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    Vary: "Accept-Encoding, Origin"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "1"
include:
  - _headers
exclude:
  - Gemfile
  - README.md
title: "!ninja"
description: There are no ninjas here!
url: https://not.ninja
twitter:
  username: WeAreNotNinja
logo: /assets/img/logo/base-fill/not-ninja-logo-fill-512x512.png
lang: en
google_analytics_account: UA-97902449-1
social:
  name: "!ninja"
  links:
    - https://twitter.com/WeAreNotNinja
    - https://www.facebook.com/WeAreNotNinja
    - https://github.com/NotNinja
navigation:
  social_links:
    - href: mailto:contact@not.ninja
      class_prefix: email
      icon: fa-envelope-square
      text: Email
    - href: https://github.com/NotNinja
      class_prefix: github
      icon: fa-github-square
      text: GitHub
    - href: https://slack.not.ninja
      class_prefix: slack
      icon_stack:
        - fa-square
        - fa-slack fa-inverse
      text: Slack
    - href: https://twitter.com/WeAreNotNinja
      class_prefix: twitter
      icon: fa-twitter-square
      text: Twitter
    - href: https://www.facebook.com/WeAreNotNinja
      class_prefix: facebook
      icon: fa-facebook-square
      text: Facebook
